# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('seo_title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'deleted')], default=1)),
                ('created', models.DateField()),
                ('update', models.DateField()),
                ('published', models.DateField()),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
