# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(editable=False),
        ),
    ]
